sudo: required
language: java
services:
- docker

jdk:
- openjdk11

notifications:
  email: false

env:
  global:
  - secure: zun1ecQUb1Y11iJ3F0C7rgkfVzD+H0pKe77jEg36x8cptOQ2EDE8vWWNFf0ek3O9phJtIwOK1vyuRRod5/Stf1ikZcSisjAtbFgr0UBsXsdr0lPK3f+qJfSD/5KR+kIMwnnqM3W55QQuOJkoTyRmy84yjUB8gr42pWOaYV6eU3es2ROjuyVEr8Ao4c40p9peSHsQzzrmNUwS9OMKiIu38zhAH3XI2u8ybsTbg7bVqXwIBZVvmli/E4acqEG6/okJzcskVZM9WFk1856755Vimaulr194s1kgMTCC+vb5a0thrF9R2uOZ92RYue9+0RrXVbU0hD48virNaKXiGBJ6hfRpw9zXzkyZxEwdRZzFEt+fppDrKXK/fzQaBocbG+g5jKvtsp6ZFri8tezlUO9y2FXjY/RZ3RDW3WnCNdvnUv4dk9lQnx0/Fsjm0YSZQYd0K06JASt4RFdBZ2jDqZwP/L5VXOcyxw3X7fOMpjnj/nBOhiQccxFiaZbzAuVw69ugn0fNNC841HGNMCBldq6pAI1YG7Fxs/qY9azipVSB4jr2LYU0iDD7gWUTPBhOGrMT1P908pX3tMFSykiEwY/2AWnnJaTeO9rVUFNRVkFArWM689cwILwuCw2X+w/hMrc3KWpfss5zYo1R4Yx0ylPtWFcN6dOfQZ7L9bczoUwlnRU=
  - secure: VVKEwiYqIV+VizhoWsxz3Q5e7SsE6wFt70UxCnIDZ2n6P+OnO9CNDYb7vYOprIRg5FHoq4tpWjWWDd+52B81bTRW7WQpvhZLDnivC77hvQCQKpWaUBGLbLbQQ532u8Y3rPDMogs/gcMOgDA9tf9FRbZrIqdbemytYjC3zeOP12VJZb1guDobv7Gaz9Hb4rlO8gRWALKqqBtFDvrCoAJH8/ItEYjAfm4H6HYbw6N8pHU7jKebuhQfj6JEhxNXRmPqtoONRdxemKcOr7XZqBJVnnDnxiLkqyeo2f5n1TLy5hSbPGdYncUegUvFwjnmW8fN3XHFAH7n8hfmmUMbYlfaBOmJvHUAh4uaHcgvLvnE1TskPRqR1EoL4Xpn78jc0kjj+49CVZJ3aHwByehZRSJyGnsY9tjFEx+GFBAwysMerAMSJ3xsYU3vRN8tG9bbRexQhTsjAJGJ1HJjLNjreRPaw9zVbFGgSNNmGT5h0hAoEIbuhQwzCtGkzfyOfUk43zO9iKodwPWxVRphumBUaV/2RXqRAadouQfd8mng+SLvkHFIWiQBjRsOgkzULYD2zRegUbnzwqS5a8rw7dhVq9FrvCHD0mFii8cg4ZCUSJk7Oj88JLZtnUl/ujP+vHG0vRrt7/Pj7f/xzqNWokFKhN5MdFoZsiActlr/pnMt75vauck=

script: ".travis/build_script.sh"

after_success: ".travis/push_script.sh"
