sudo: required
language: java
services:
- docker
jdk:
- openjdk8
notifications:
  email: false
env:
  global:
  - secure: bfPU1LXMxn39GZnIWocLu/m1FiEupvI8ApOb8VQZth0ftvPxnRW7CoJaB/3gGqv7apkiTapWV7IbIlO0sl4ARHz0KukP+llzv+aPtQKPEKNuR6CK8Bz7Vii8oqIlfQNzgOm7qduXLWLocEAcEO9ZmexvFf3M+WBLHyzQJDqaaZeA5ghoEJSMTCwWQHXDsv9l/cDTRizW0ZRUfVLJFckC+Cmz9AfHmLgMtruPk6q+z6P370xrd/pyse+PgXW3bwA2NKbA0XPM59KsDqScckxHfDf2QM9OU2UMWFJOF1RbGoPrRIZNQZ7T3QI2KLHLLF+GJ4H98RXn+xi+6WhhdUyn7cLzP19gJ5wKCeGX6Z/zP1rOXqSzdRycu0n6+v5rj0ydjVhpqVL1IzEeefvEiw4QIkBQk3tk2VvFiDNOPnhMKKLF5gJ8RbHCdVcQCBjr36rlgHNik8ZCpOpYve0kbpkQC45OvB8Bhl5M5nWmDe8nLcCGoM7R4lCS7q3QaOlMAcW3WW3pTDy/odWiKCLIKcp6RvO6DdhyKDoD3H1ge8R9QBomZeBdu/RaiS45l9hbdOifnTa8hg3xO5Lvj564Boz5C/cmlNQu5+nfDnzykjIAG9cPbYbyjq7r00S0E4+4seTskoURnbZBF8St5Y9nnzUvMVWizXFNpZbOeXFwzQl/8M8=
  - secure: SJNiamWLHLI1KlegZk5HEG3DU78d7MNgVv0v+lP09f70qKTJ/lIx6vqaGoI3HxebPF1eA9PwoGZTq5Mjci+CK00L4K2fmbZhSPcAF6P1UCPE/fIByXs0lkar3HXMF4wJQRMMjk7y6J74lJ7OEmUFcadCvZMKciBEj9Wbj4Y8VNVEYmCnklcShc0Q3vlCMJSoBjlHxPop8UmG/sWewKbGqvEa1SHPAjGWja5lR/1Hi6Fs98tryw9my/A9QCNZbCIkrNbHRcrPxaZztLf6JW9uvv2wJIHsrKfOEMqjjWFWVan+md74D0watLZ95Gy/FMJ2vxeId/yu/CHviwsUdU7fs6kXseWtJ4QeD/yUhsqqncHjDYNZPo6rxJ96GJ1nrSsokbA2EGAxEQYKXw2xgZci08Qqhq4xvHKhtXm/ISgucJ8sTWUB/z1hLzdXxvYPxaDHZWOQ6/L/mCuLWATTlScFe7WXk1Avb+HyF5ecyxuusToA9wo5Z3pyYRCcs0B3SAKXMbh3JoRR2QCqCiLmFjLErBLmuDS3pTGRWtENzUIYZ1ZmSv8Ip+c8yWHGWYSwJvuTHP8I5J/pHcihoin6nsC1KCh27YWzAymtLcGSBJ3ebq9lypOD8cCld1BGmdGHaPBh5IjOdfQri/FN2o95keiisraR84KBYSF1sqyWV6tozlE=
before_install:
- chmod +x .travis/build_script.sh
- chmod +x .travis/push_script.sh
script: ".travis/build_script.sh"
after_success: ".travis/push_script.sh"
