sudo: required
language: java
services:
  - docker

jdk:
- openjdk8

notifications:
  email: false

env:
  global:
  - secure: bWiEpDJ04ku4zMWaUPrbC4lLbbMTVBFbSE7DrydPHTzyPsYeocxE4kUzQD1cdnd8bq2oyqAEz2jEq2phzvN0l3eslvdk6Ld1HNprE9yahwND2O9i71nPmYdMu3pWjYDVh5ezlB17LM2saJcrko62uHqWs4BhLmGZz0Nfxkm6RKi0Xu5a7SBsMvKas+5JA/3DKrfjYSegcb9Xl4GyaEcdyeLv91a+A3wvqLDbScwlyFnEw1axBHsy7E7P4FTaqZgkGW8+/yqpS48hsJsmzzvKR9iMt0t2TTkg07dCS2zSjp/LDytpIzDArJEmyivefHT/M+X3vanFCx5MDQIOaQ4oWBCI7SuZ3zXPLy0iB/KxgFPQk2afCTSK2uWkUrAqIGf0/F+fKaO+xz4DViaoTO3JgcIJ8/3aXjNxBXkvbO7M1BBqvv8L/8/iTfemrsSx8ofKNpl+oQJRza9kLK9O8vJrJXTis9vkHHKKGzBDMuZxEEGJAhalyq2NPhoeZ2EaMKhW7e71Y8OvuzwbpuJRSsRtFmNBbPUl/CFLU0Dz9N0vX6MwrAh7Wu2FWQCPD/4p3IgSDwTdjQqRvzan5bPUVuQt2sazXwPUKlKD503k9NyvERl/VWT72hhMqINdLtQiBQBbcfjMGuq9k53hd/PA8CF9j5g40RRiT08FFp+YRMSnTAQ=
  - secure: 2YxjXvPXD4APycLAT5OUne6V4UfTfzxEeyMLMiIrUB0U6fYTd6dCh/c2slGZciqUssDaeW8eYFcwhZQx9A/4JliZHYeD9bhKqw4NuZWisN4cyKJN/DEqnicfIy7tVc37lKcik27rZUm/pWiOzlxH73dnoUi8rp9X8yWIoGRNjBh1Uh5SEJgqY6zy4r68e1MF0410R3fpkVP9KMsAUuoaNtRqsCXEA/rTha8alRKZAJZohbZXwkY2Pcc4pFyccS/Ae0IK6IBOoYo2DZWy7IDOFLEkfTsRZBveuj8FguD6X74AcAAQYr58HF2wDowTSaj6ZdbGRfV36kBWJAiAoH1AwiI+72LNslPgpMu74Rl4iwU7+yHjAynVBaGZxhJ2SLO0/NSqZNG8tWaCqBvMqfEWc/4UkEiNSRcnxmeECPcnPHm9CV5k48iMkKmklLUEz2riXEv47SGD+ulq4V7FeJQkQL0oflXWGyeZrPCS+Ng1X5ABbtgDT/7CELzCMtQcKwzLevU961uKtw+teRUFY4uy2vJbo+Sum51meXzvE5gURCbzeD5BHb/jZ1V/KS9SsHb3/OFTw+MVmeB0S/Ku+7eeZNXM8k6QJkqfQniEKLdWI+81ObCi6rd96LikSXvN0tjDnn0Y101TRQRONfD5+IdIIqTBmRs8YcCzS7FcxNjyq+U=

before_install:
  - chmod +x build_script.sh
  - chmod +x push_script.sh

script: .travis/build_script.sh

after_success: .travis/push_script.sh
